#!/usr/bin/env bash
# shellcheck shell=bash
set -euo pipefail

# K8s 默认环境变量
TULAN_K8S_DIR="${TULAN_K8S_DIR:-$(tulan_get_home)/scripts/k8s}"
TULAN_K8S_CERT_OUT="${TULAN_K8S_CERT_OUT:-/etc/certs}"
TULAN_K8S_SITE_DOMAIN="${TULAN_K8S_SITE_DOMAIN:-k8s.local.tulan.wang}"
TULAN_K8S_RANCHER_DATA="${TULAN_K8S_RANCHER_DATA:-/opt/rancher-data}"
TULAN_K8S_RANCHER_IMAGE="${TULAN_K8S_RANCHER_IMAGE:-rancher/rancher:v2.8.5}"
TULAN_K8S_REGISTRY_MIRROR="${TULAN_K8S_REGISTRY_MIRROR:-${TULAN_DOCKER_REGISTRY_MIRROR:-https://hub.coding-space.cn}}"
TULAN_K8S_CONTAINER="${TULAN_K8S_CONTAINER:-rancher}"
TULAN_K8S_HTTP_PORT="${TULAN_K8S_HTTP_PORT:-8080:80}"
TULAN_K8S_HTTPS_PORT="${TULAN_K8S_HTTPS_PORT:-8443:443}"
TULAN_K8S_UPGRADE_DEFAULT="${TULAN_K8S_UPGRADE_DEFAULT:-rancher/rancher:v2.13.3}"
